spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/deliverywatch
    username: postgres
    password: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration/metrics
    table: flyway_history_metrics
    baseline-on-migrate: true
    baseline-version: 0
    schemas: public
  kafka:
    bootstrap-servers: localhost:29092
    streams:
      application-id: deliverywatch-metrics
      state-dir: /tmp/kstreams/${spring.kafka.streams.application-id}-${HOSTNAME}
      properties:
        commit.interval.ms: 10000
app:
  kafka:
    input-topic: delivery.order.events.v1
  windows:
    size-minutes: 1
  alerts:
    sla-threshold: 90.0

server:
  port: 8081
