server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/deliverywatch
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration/order
    table: flyway_history_order
    baseline-on-migrate: true
    baseline-version: 0

  autoconfigure:

  jackson:
    serialization:
      write-dates-as-timestamps: false

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:29092

app:
  kafka:
    topic: delivery.order.events.v1

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: INFO
    com.example.orderapi: INFO
