server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/deliverywatch
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration/order
    table: flyway_history_order
    baseline-on-migrate: true
    baseline-version: 0

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true



app:
  kafka:
    bootstrap: localhost:29092
    topic: orders
